feat(react-auth): add test
Atlantis-Lab/reactjs pull request #66
Opened 2021-01-13 17:49 UTC by TFK70

2021-01-13 18:05 UTC, themetronome approved these changes

2021-01-13 18:31 UTC, TorinAsakura requested changes

2021-01-13 18:31 UTC, TorinAsakura commented on packages/react-auth/__tests__/react-auth.test.tsx
> +describe('Test suit for react-auth package', function() {
https://stackoverflow.com/questions/52735032/warning-unexpected-unnamed-function-func-names-under-eslint-rule

2021-01-13 18:31 UTC, TorinAsakura commented on packages/react-auth/package.json
> +    "@atlantis-lab/jest-config": "^0.1.2",
замени на @atlantis-lab/config и вынеси в рут

2021-01-13 18:31 UTC, TorinAsakura commented on packages/react-auth/package.json
>    "devDependencies": {
разберись с зависимостями
зачем тебе пир зависимости?
почему необходимые для запуска зависимости находятся в dev?

2021-01-14 10:45 UTC, TorinAsakura approved these changes

2021-01-14 10:46 UTC, merged